# -*- coding: utf-8 -*-
"""Computation_with_NumPy_and_N_Dimensional_Arrays_(start).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KdHoW3N6WKFfnwL08hjvYVpC_46A332o

# Introduction

In this notebook we'll learn how to use NumPy to work with numerical data.

<img src="https://i.imgur.com/dZ1XE9o.png" width=400>

# Import Statements
"""

import numpy as np

import matplotlib.pyplot as plt
from scipy import dataset # contains an image of a racoon!
from PIL import Image # for reading image files

"""# Understanding NumPy's ndarray

NumPy's most amazing feature is the **powerful** ndarray.

<img src="https://i.imgur.com/1IUqnxX.png" width=200>

#### 1-Dimensional Arrays (Vectors)
"""

my_array = np.array([1.6, 2.5, 7.6, 4.3, 9.6])
my_array.shape

my_array[2]

my_array.ndim

"""#### 2-Dimensional Arrays (Matrices)"""

array_2d = np.array([[1, 2, 3, 9],
                     [5, 6, 7, 8]])

print(f"Its Shape is {array_2d.shape}.")

print(f"It has {array_2d.shape[0]} rows")
print(f"\t and {array_2d.shape[1]} columns.")

print(f"array_2d has {array_2d.ndim} dimensions.")

print(array_2d)

# access the 3rd value in the 2nd row
print(array_2d[1, 2])

# access all the value in the first row
print(array_2d[0, :])

"""#### N-Dimensional Arrays (Tensors)

**Challenge**:
* How many dimensions does the array below have?
* What is its shape (i.e., how many elements are along each axis)?
* Try to access the value `18` in the last line of code.
* Try to retrieve a 1 dimensional vector with the values `[97, 0, 27, 18]`
* Try to retrieve a (3,2) matrix with the values `[[ 0,  4], [ 7,  5], [ 5, 97]]`

*Hint*: You can use the `:` operator just as with Python Lists.
"""

mystery_array = np.array([
                          [
                           [0, 1, 2, 3],
                           [4, 5, 6, 7]
                          ],

                          [
                           [7, 86, 6, 98],
                           [5, 1, 0, 4]
                          ],

                          [
                           [5, 36, 32, 48],
                           [97, 0, 27, 18]
                          ]
                         ])

# Note all the square brackets!

# How many dimensions does the array below have?
print(f'We have {mystery_array.ndim} dimensions')

# What is its shape (i.e., how many elements are along each axis)?
print(f'The shape is {mystery_array.shape}')

"""The shape is (3, 2, 4), so we have 3 elements along axis #0, 2 elements along axis #1 and 4 elements along axis #2.

Iska shape (3, 2, 4) hai. Matlab:

3 blocks hain,

Har block me 2 rows hain,

Har row me 4 columns hain.
"""

# Try to access the value 18 in the last line of code.
print(mystery_array[2, 1, 3])

"""To access the value 18 we, therefore, have to provide three different indices - one for each axis. As such, we locate the number at index 2 for the first axis, index number 1 for the second axis, and index number 3 for the third axis."""

# Try to retrieve a 1 dimensional vector with the values [97, 0, 27, 18]
print(mystery_array[2, 1, :])

"""The values [97, 0, 27, 18] live on the 3rd axis and are on position 2 for the first axis and position 1 on the second axis"""

# Try to retrieve a (3,2) matrix with the values [[ 0, 4], [ 7, 5], [ 5, 97]]
print(mystery_array[:, :, 0])

"""Yahan teen index dimension hain:

* First colon : → select all 3 blocks

* Second colon : → select all 2 rows from each block

* 0 → har row ka sirf pehla column (0th index)

# NumPy Mini-Challenges

#### **Challenge 1**: Use [`.arange()`](https://numpy.org/devdocs/reference/generated/numpy.arange.html)to createa a vector `a` with values ranging from 10 to 29. You should get this:

`print(a)`

`[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]`
"""

a = np.arange(10, 30)
print(a)

"""#### **Challenge 2**: Use Python slicing techniques on `a` to:
* Create an array containing only the last 3 values of `a`
* Create a subset with only the 4th, 5th, and 6th values
* Create a subset of `a` containing all the values except for the first 12 (i.e., `[22, 23, 24, 25, 26, 27, 28, 29]`)
* Create a subset that only contains the even numbers (i.e, every second number)
"""

print(f"3 last value of a: {a[-3:]}")
print(f"subset with only the 4th, 5th, and 6th values: {a[3:6]}")
print(f"a subset of a containing all the values except for the first 12: {a[12:]}")
print(f"subset that only contains the even numbers: {a[0: :2]}")

"""#### **Challenge 3**:Reverse the order of the values in `a`, so that the first element comes last:

`[29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10]`


If you need a hint, you can check out this part of the [NumPy beginner's guide](
https://numpy.org/devdocs/user/absolute_beginners.html#how-to-reverse-an-array)
"""

a = [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]
print(f"Reversed order: {np.flip(a)}")

"""#### **Challenge 4**:

"""

print("Method - 1 for data science:")
array_1d = np.array([6,0,9,0,0,5,0])
non_zero_indices = np.nonzero(array_1d)
print(f"all the indices of the non-zero elements: {non_zero_indices}")

print("\n")
print("Method - 2 for beginner:")
array_1d = [6,0,9,0,0,5,0]
non_zero_indices = []
for i in range(len(array_1d)):
  if array_1d[i] != 0:
    non_zero_indices.append(i)
print(f"all the indices of the non-zero elements: {non_zero_indices}")

"""#### **Challenge 5**: Use NumPy to generate a 3x3x3 array with random numbers

Hint: Use the [`.random()` function](https://numpy.org/doc/stable/reference/random/index.html?highlight=random#module-numpy.random)
"""

from numpy.random import random
z = random((3,3,3))
print(z)
print("\n")

z = np.random.random((3,3,3)) # without an import statement
print(z.shape)


print("\n")
rng = np.random.default_rng()
rng.integers(low=0, high=30, size=[3,3,3])

"""The .random() function is another way to quickly create a ndarray, just like .arange(). The .random() function lives under np.random so you'll either have to import random

from numpy.random import random
z = random((3,3,3))
z
or use the full path to call it.

z = np.random.random((3,3,3)) # without an import statement
print(z.shape)
z

#### **Challenge 6**: Use [`.linspace()`](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html) to create a vector `x` of size 9 with values spaced out evenly between 0 to 100 (both included).
"""

x = np.linspace(0, 100, num=9)
print(x)
x.shape

"""The .linspace() function is very similar to .arange() and great for generating evenly spaced numbers over an interval.

#### **Challenge 7**: Use [`.linspace()`](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html) to create another vector `y` of size 9 with values between -3 to 3 (both included). Then plot `x` and `y` on a line chart using Matplotlib.
"""

x = np.linspace(0, 100, num=9)
# y = np.linspace(start=-3, stop=3, num=9, endpoint=True)
y = np.linspace(start=-3, stop=3, num=9)
plt.plot(x, y)
plt.show()

"""#### **Challenge 8**: Use NumPy to generate an array called `noise` with shape 128x128x3 that has random values. Then use Matplotlib's [`.imshow()`](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.imshow.html) to display the array as an image."""

noise = np.random.random((128, 128, 3))
print(noise.shape)
plt.imshow(noise)

print("\n")
rng = np.random.default_rng()
noise = rng.integers(low=0, high=264, size=[128,128,3])
plt.imshow(noise)

"""# Linear Algebra with Vectors"""

v1 = np.array([4, 5, 2, 7])
v2 = np.array([2, 1, 3, 3])
print(v1 + v2)
print(v1 - v2)
print(v1 * v2)

# Python Lists vs ndarrays
list1 = [4, 5, 2, 7]
list2 = [2, 1, 3, 3]

print(list1 + list2)

print(list1 - list2) # show error: list subtraction is not allowed

print(list1 * list2) # show error: list multiplication is not allowed

"""# Broadcasting and Scalars

"""

array_2d = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8]])

array_2d + 10    # adds 10 in every element.

array_2d * 5     # multiplication by 10 with every element.

"""# Matrix Multiplication with @ and .matmul()

<img src=https://i.imgur.com/LCdhmi8.png width=350>
"""

a1 = np.array([[1, 3],
               [0, 1],
               [6, 2],
               [9, 7]])

b1 = np.array([[4, 1, 3],
               [5, 8, 5]])

print(f'{a1.shape}: a has {a1.shape[0]} rows and {a1.shape[1]} columns.')
print(f'{b1.shape}: b has {b1.shape[0]} rows and {b1.shape[1]} columns.')
print('Dimensions of result: (4x2)*(2x3)=(4x3)')

"""**Challenge**: Let's multiply `a1` with `b1`. Looking at the wikipedia example above, work out the values for c12 and c33 on paper. Then use the [`.matmul()`](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html) function or the `@` operator to check your work."""

result = np.matmul(a1, b1)
print(f"matrix 'result' has {result.shape[0]} rows and {result.shape[1]} columns.")
result

a1 @ b1

"""# Manipulating Images as ndarrays

"""

from scipy import datasets
image = datasets.ascent()
image

"""We can now clearly see that we're dealing with a ndarray. And it's a 3 dimensional array at that."""

plt.imshow(image)    # without using cmap='gray' attribut

"""**Challenge**: What is the data type of `img`? Also, what is the shape of `img` and how many dimensions does it have? What is the resolution of the image?"""

# What is the data type of img?
type(image)

# what is the shape of `img` and how many dimensions does it have?
print(image.shape)
np.ndim(image)

"""There are three matrices stacked on top of each other - one for the red values, one for the green values and one for the blue values. Each matrix has a 512 rows and 512 columns, which makes sense since 512x512 is the resolution of the image.

**Challenge**: Convert the image to black and white. The values in our `img` range from 0 to 255.
* Divide all the values by 255 to convert them to sRGB, where all the values are between 0 and 1.
* Next, multiply the sRGB array by the `grey_vals` to convert the image to grey scale.
* Finally use Matplotlib's [`.imshow()`](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.imshow.html) together with the colormap parameter set to gray `cmap=gray` to look at the results.
"""

sRGB_array = image / 255

"""Here NumPy will use broadcasting to divide all the values in our ndarray by 255.


"""

gray_vals = np.array([0.2126, 0.0722])

image_gray = sRGB_array @ gray_vals

plt.imshow(image, cmap='gray')

"""**Challenge**: Can you manipulate the images by doing some operations on the underlying ndarrays? See if you can change the values in the ndarray so that:

1) You flip the grayscale image upside down

<img src=https://i.imgur.com/r36CigD.png>

2) Rotate the colour image

<img src=https://i.imgur.com/IiNylco.png>

3) Invert (i.e., solarize) the colour image. To do this you need to converting all the pixels to their "opposite" value, so black (0) becomes white (255).

<img src=https://i.imgur.com/cfFbuex.png>

#### Challenge Solutions
"""

plt.imshow(np.flip(image), cmap='gray')

plt.imshow(np.rot90(image), cmap='gray')

"""Inverting the colour image is a bit more tricky. It involved making use of NumPy's ability to broadcast when doing operations with a scalar. In this case, our scalar is 255 - the maximum value for a pixel in RGB (see gif at the very top). If we subtract the values of our img from 255, then we get the opposite value for each pixel:


"""

solar_image = 255 - image
plt.imshow(solar_image, cmap='gray')

"""# Use your Own Image!"""

file_name = 'yummy_macarons.jpg'

"""#### Use PIL to open"""

my_img = Image.open(file_name)
img_array = np.array(my_img)

print(img_array.ndim)
img_array.shape

plt.imshow(img_array)

plt.imshow(255 - img_array)

plt.imshow(np.rot90(img_array))

plt.imshow(np.flip(img_array))