# -*- coding: utf-8 -*-
"""Seaborn_and_Linear_Regression_(start).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f4lzTHW59M9-yn1qBB21OuGMOUjK8pZU

# Introduction

Do higher film budgets lead to more box office revenue? Let's find out if there's a relationship using the movie budgets and financial performance data that I've scraped from [the-numbers.com](https://www.the-numbers.com/movie/budgets) on **May 1st, 2018**.

<img src=https://i.imgur.com/kq7hrEh.png>

# Import Statements
"""

import pandas as pd
import matplotlib.pyplot as plt

import seaborn as sns
from sklearn.linear_model import LinearRegression

"""# Notebook Presentation"""

pd.options.display.float_format = '{:,.2f}'.format

from pandas.plotting import register_matplotlib_converters
register_matplotlib_converters()

"""# Read the Data"""

data = pd.read_csv('cost_revenue_dirty.csv')

"""# Explore and Clean the Data

**Challenge**: Answer these questions about the dataset:
1. How many rows and columns does the dataset contain?
2. Are there any NaN values present?
3. Are there any duplicate rows?
4. What are the data types of the columns?
"""

# How many rows and columns does the dataset contain?
print(f"{data.shape[0]} Rows")
print(f"{data.shape[1]} Columns")
data.head()

data.tail()

# Are there any NaN values present?
print(f"Any NaN values among the data? {data.isna().values.any()}")
duplicate_rows = data[data.duplicated()]
print(f"Number of duplicates? {len(duplicate_rows)}")

# Are there any duplicate rows?
print(f"Any duplicates? {data.duplicated().values.any()}")

# What are the data types of the columns?
data.info()

"""### Data Type Conversions

**Challenge**: Convert the `USD_Production_Budget`, `USD_Worldwide_Gross`, and `USD_Domestic_Gross` columns to a numeric format by removing `$` signs and `,`.
<br>
<br>
Note that *domestic* in this context refers to the United States.
"""

chars_to_remove = ['$', ',']
columns_to_clean = ['USD_Production_Budget',
                    'USD_Worldwide_Gross',
                    'USD_Domestic_Gross']

for col in columns_to_clean:
  for char in chars_to_remove:
    # Replace each charachter with an empty string
    data[col] = data[col].astype(str).str.replace(char, "")
  # Conver column to numeric data type
  data[col] = pd.to_numeric(data[col])

data.head()

"""**Challenge**: Convert the `Release_Date` column to a Pandas Datetime type."""

data.Release_Date = pd.to_datetime(data.Release_Date )
data.head()

"""### Descriptive Statistics

**Challenge**:

1. What is the average production budget of the films in the data set?
2. What is the average worldwide gross revenue of films?
3. What were the minimums for worldwide and domestic revenue?
4. Are the bottom 25% of films actually profitable or do they lose money?
5. What are the highest production budget and highest worldwide gross revenue of any film?
6. How much revenue did the lowest and highest budget films make?
"""

# What is the average production budget of the films in the data set?
# What is the average worldwide gross revenue of films?
# What were the minimums for worldwide and domestic revenue?
# Are the bottom 25% of films actually profitable or do they lose money?
# What are the highest production budget and highest worldwide gross revenue of any film?
data.describe()

# which film was the lowest budget film in the dataset?
data[data.USD_Production_Budget == 1100.00]

# which film was the highest budget film in the dataset?
data[data.USD_Production_Budget == 425000000.00]

"""# Investigating the Zero Revenue Films

**Challenge** How many films grossed $0 domestically (i.e., in the United States)? What were the highest budget films that grossed nothing?
"""

# How many films grossed $0 domestically (i.e., in the United States)?
zero_domestic = data[data.USD_Domestic_Gross == 00.00]
print(f'Number of films that grossed $0 domesticalyy: {len(zero_domestic)}')

# What were the highest budget films that grossed nothing?
zero_domestic.sort_values('USD_Production_Budget', ascending=False)

"""**Challenge**: How many films grossed $0 worldwide? What are the highest budget films that had no revenue internationally?"""

# How many films grossed $0 worldwide?
zero_worldwide = data[data.USD_Worldwide_Gross == 00]
print(f'Number of films that grossed $0 domesticalyy: {len(zero_worldwide)}')

# What are the highest budget films that had no revenue internationally?
zero_worldwide.sort_values('USD_Production_Budget', ascending=False)

"""### Filtering on Multiple Conditions"""

international_release = data.loc[(data.USD_Domestic_Gross == 00) & (data.USD_Worldwide_Gross != 00)]
print(f"Number of international release: {len(international_release)}")
international_release.head()

"""**Challenge**: Use the [`.query()` function](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.query.html) to accomplish the same thing. Create a subset for international releases that had some worldwide gross revenue, but made zero revenue in the United States.

Hint: This time you'll have to use the `and` keyword.
"""

international_release = data.query('USD_Domestic_Gross == 0 and USD_Worldwide_Gross != 0')
print(f'Number of international release: {len(international_release)}')
international_release.tail()

"""### Unreleased Films

**Challenge**:
* Identify which films were not released yet as of the time of data collection (May 1st, 2018).
* How many films are included in the dataset that have not yet had a chance to be screened in the box office?
* Create another DataFrame called data_clean that does not include these films.
"""

# Date of Data Collection
scrape_date = pd.Timestamp('2018-5-1')

future_release = data[data.Release_Date >= scrape_date]
print(f"Number of unreleased movies: {len(future_release)}")
future_release

# Create another DataFrame called data_clean that does not include these films.
data_clean = data.drop(future_release.index)

"""### Films that Lost Money

**Challenge**:
What is the percentage of films where the production costs exceeded the worldwide gross revenue?
"""

# using the .loc[] property:
money_losing = data_clean.loc[data_clean.USD_Production_Budget > data_clean.USD_Worldwide_Gross]
print(f"Number of moving losed money: {(money_losing.shape[0]/data_clean.shape[0])*100}%")

# using the .query() function
money_losing = data_clean.query('USD_Production_Budget > USD_Worldwide_Gross')
print(f"Number of moving losed money: {(len(money_losing)/len(data_clean))*100}%")

"""# Seaborn for Data Viz: Bubble Charts"""

sns.scatterplot(data=data_clean,
                x='USD_Production_Budget',
                y='USD_Worldwide_Gross')

"""That should look familiar. Because Seaborn is built on top of Matplotlib, we can dive into the Matplotlib layer anytime to configure our chart. For example, we can increase the size of our figure:"""

plt.figure(figsize=(8,4), dpi=200)
sns.scatterplot(data=data_clean,
                x='USD_Production_Budget',
                y='USD_Worldwide_Gross')
plt.show()

"""And to style our chart we can simply configure the Axes object that is returned from sns.scatterplot()."""

plt.figure(figsize=(8,4), dpi=200)

ax = sns.scatterplot(data=data_clean,
                     x='USD_Production_Budget',
                     y='USD_Worldwide_Gross')

ax.set(ylim=(0, 3000000000),
       xlim=(0, 450000000),
       ylabel='Revenue in $ billions',
       xlabel='Budget in $100 millions')

plt.show()

"""Here we're diving into the Matplotb layer to set the limits on the axes and change the labels.

### Plotting Movie Budget over Time

**Challenge**: Try to create the following Bubble Chart:

write the code to replicate this chart? Notice how we are actually representing THREE dimensions in this chart: the budget, the release date, and the worldwide revenue. This is what makes bubble charts so awesomely informative.

<img src=https://i.imgur.com/8fUn9T6.png>
"""

plt.figure(figsize=(8,4), dpi=200)

with sns.axes_style('darkgrid'):
  ax = sns.scatterplot(data=data_clean,
                       x='Release_Date',
                       y='USD_Production_Budget',
                       hue='USD_Worldwide_Gross',
                       size='USD_Worldwide_Gross')

  ax.set(ylim=(0, 450000000),
         xlim=(data_clean['Release_Date'].min(), data_clean['Release_Date'].max()),
         xlabel='Year',
         ylabel='Budget in $100 milllions')

"""# Converting Years to Decades Trick

**Challenge**: Create a column in `data_clean` that has the decade of the release.

<img src=https://i.imgur.com/0VEfagw.png width=650>

Here's how:
1. Create a [`DatetimeIndex` object](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DatetimeIndex.html) from the Release_Date column.
2. Grab all the years from the `DatetimeIndex` object using the `.year` property.
<img src=https://i.imgur.com/5m06Ach.png width=650>
3. Use floor division `//` to convert the year data to the decades of the films.
4. Add the decades as a `Decade` column to the `data_clean` DataFrame.

* To create a DatetimeIndex, we just call the constructor and provide our release date column as an argument to initialise the DatetimeIndex object. Then we can extract all the years from the DatetimeIndex.
"""

dt_index = pd.DatetimeIndex(data_clean['Release_Date'])
years = dt_index.year

"""* Now, all we need to do is convert the years to decades. For that, we will use floor division (aka integer division). The difference to regular division is that the result is effectively rounded down."""

# How to convert the year deacade
decades = years // 10*10
data_clean['Decade'] = decades
data_clean.head()

"""### Separate the "old" (before 1969) and "New" (1970s onwards) Films

**Challenge**: Create two new DataFrames: `old_films` and `new_films`
* `old_films` should include all the films before 1970 (up to and including 1969)
* `new_films` should include all the films from 1970 onwards
* How many films were released prior to 1970?
* What was the most expensive film made prior to 1970?
"""

old_films = data_clean[data_clean.Decade <= 1960]
new_films = data_clean[data_clean.Decade > 1960]

"""* The cut-off for our calculation is 1960 in the Decade column because this will still include 1969. When we inspect our old_films DataFrame we see that it only includes 153 films. As we saw in the bubble chart, the bulk of films in the dataset have been released in the last 30 years."""

old_films.describe()

old_films.sort_values('USD_Production_Budget', ascending=False).head()

"""# Seaborn Regression Plots"""

sns.regplot(data=data_clean,
            x='USD_Production_Budget',
            y='USD_Worldwide_Gross')

"""* This creates a scatter plot and draws a linear regression line together with the confidence interval at the same time.

* To style the chart further, we can once again, drop into the Matplotlib layer and supply keyword arguments as dictionaries. We can customise the scatter plot (e.g., by changing the transparency of the dots) and the regression line itself (e.g., by changing the colour).


"""

plt.figure(figsize=(8, 4), dpi=200)

with sns.axes_style("whitegrid"):
  sns.regplot(data=old_films,
              x='USD_Production_Budget',
              y='USD_Worldwide_Gross',
              scatter_kws = {'alpha': 0.4},
              line_kws = {'color': 'black'})

"""**Challenge**: Use Seaborn's `.regplot()` to show the scatter plot and linear regression line against the `new_films`.
<br>
<br>
Style the chart

* Put the chart on a `'darkgrid'`.
* Set limits on the axes so that they don't show negative values.
* Label the axes on the plot "Revenue in \$ billions" and "Budget in \$ millions".
* Provide HEX colour codes for the plot and the regression line. Make the dots dark blue (#2f4b7c) and the line orange (#ff7c43).

Interpret the chart

* Do our data points for the new films align better or worse with the linear regression than for our older films?
* Roughly how much would a film with a budget of $150 million make according to the regression line?
"""

plt.figure(figsize=(8,4), dpi=200)
with sns.axes_style('darkgrid'):
  ax = sns.regplot(data=new_films,
                   x='USD_Production_Budget',
                   y='USD_Worldwide_Gross',
                   color='#2f4b7c',
                   scatter_kws = {'alpha': 0.3},
                   line_kws = {'color': '#ff7c43'})

  ax.set(ylim=(0, 3000000000),
         xlim=(0, 450000000),
         ylabel='Revenue in $ billions',
         xlabel='Budget in $100 millions')

"""# Run Your Own Regression with scikit-learn

$$ REV \hat ENUE = \theta _0 + \theta _1 BUDGET$$
"""

regression = LinearRegression()

# Expalanatory feature(s) and variable(s)
X = pd.DataFrame(new_films, columns=['USD_Production_Budget'])

# Response variable or Target
Y = pd.DataFrame(new_films, columns=['USD_Worldwide_Gross'])

# Our LinearRegression does not like receiving Pandas Series (e.g., new_films.USD_Production_Budget),
# so I've created some new DataFrames here.

# Find the best fit line
regression.fit(X, Y)

# Theta-zero
regression.intercept_

# Theta-one
regression.coef_

# R-squared
regression.score(X, Y)

"""**Challenge**: Run a linear regression for the `old_films`. Calculate the intercept, slope and r-squared. How much of the variance in movie revenue does the linear model explain in this case?"""

X = pd.DataFrame(old_films, columns=['USD_Production_Budget'])
Y = pd.DataFrame(old_films, columns=['USD_Worldwide_Gross'])

regression.fit(X, Y)

print(f'the slope coefficient is: {regression.coef_[0]}')
print(f'the intercept is: {regression.intercept_[0]}')
print(f'the r-squared is: {regression.score(X, Y)}')



"""# Use Your Model to Make a Prediction

We just estimated the slope and intercept! Remember that our Linear Model has the following form:

$$ REV \hat ENUE = \theta _0 + \theta _1 BUDGET$$

**Challenge**:  How much global revenue does our model estimate for a film with a budget of $350 million?
"""

budget = 350000000
revenue_estimate = regression.intercept_[0] + regression.coef_[0,0] * budget
revenue_estimate = round(revenue_estimate, -6)

print(f'The estimated revenue for a $350 film is around ${revenue_estimate:.10} .')

"""* (The colon : and dot . in a print statement is quite handy for controlling the number of digits you'd like to show up in the output)"""